### ISSUE TITLE
Integration with raco

### ISSUE THREAD

**Issue by soegaard** [mythical-linux/rktfetch#4]
Great idea, which makes both bug reports and benchmark writeups easier.

An idea: The `raco` command line tool allows "plugins", so it is possible
to make rktfetch a raco subcommand:

    raco rktfetch

More information here:

    https://docs.racket-lang.org/raco/command.html?q=raco

**Comment by xgqt** [comment]
Closed. Thanks for reporting.
This gave me a idea to count installed racket packages :D

**Comment by xgqt** [comment]
> This gave me a idea to count installed racket packages :D

https://github.com/mythical-linux/rktfetch/commit/e59d8e1c9a207825ded2c0dec1fba5879c4d94b5
